# Generated by Django 3.1.1 on 2020-11-19 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0011_like'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
