# Generated by Django 3.1.1 on 2020-11-26 10:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0012_delete_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posting',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
